// frontend/src/utils/mockCompanies.js
const mockCompanies = [
  {
    id: 1,
    name: "NeuralLeap",
    website: "https://openai.com",
    industry: "AI",
    location: "San Francisco, CA",
    founded: "2021",
    employees: "25-50",
    description: "Building next-generation neural networks for enterprise automation",
    logo: "https://logo.clearbit.com/openai.com",
  },
  {
    id: 2,
    name: "FinFlow",
    website: "https://stripe.com",
    industry: "Fintech",
    location: "New York, NY",
    founded: "2020",
    employees: "50-100",
    description: "Modern treasury management API for businesses",
    logo: "https://logo.clearbit.com/stripe.com",
  },
  {
    id: 3,
    name: "MediScan AI",
    website: "https://health.com",
    industry: "HealthTech",
    location: "Boston, MA",
    founded: "2022",
    employees: "10-25",
    description: "AI-powered medical imaging diagnostics",
    logo: "https://logo.clearbit.com/health.com",
  },
  {
    id: 4,
    name: "CloudCanvas",
    website: "https://aws.amazon.com",
    industry: "SaaS",
    location: "Seattle, WA",
    founded: "2019",
    employees: "100-250",
    description: "Visual cloud infrastructure management platform",
    logo: "https://logo.clearbit.com/aws.amazon.com",
  },
  {
    id: 5,
    name: "EcoCharge",
    website: "https://tesla.com",
    industry: "CleanTech",
    location: "Austin, TX",
    founded: "2021",
    employees: "15-30",
    description: "Smart EV charging infrastructure with grid optimization",
    logo: "https://logo.clearbit.com/tesla.com",
  },
  {
    id: 6,
    name: "EduFlex",
    website: "https://khanacademy.org",
    industry: "EdTech",
    location: "Chicago, IL",
    founded: "2020",
    employees: "30-60",
    description: "Adaptive learning platform for K-12 education",
    logo: "https://logo.clearbit.com/khanacademy.org",
  },
  {
    id: 7,
    name: "SecureShare",
    website: "https://cloudflare.com",
    industry: "Cybersecurity",
    location: "Washington, DC",
    founded: "2018",
    employees: "40-80",
    description: "Zero-knowledge proof file sharing for enterprises",
    logo: "https://logo.clearbit.com/cloudflare.com",
  },
  {
    id: 8,
    name: "DataForge",
    website: "https://databricks.com",
    industry: "AI",
    location: "Denver, CO",
    founded: "2022",
    employees: "8-20",
    description: "Synthetic data generation for ML training",
    logo: "https://logo.clearbit.com/databricks.com",
  },
  {
    id: 9,
    name: "PayRails",
    website: "https://wise.com",
    industry: "Fintech",
    location: "Miami, FL",
    founded: "2021",
    employees: "20-40",
    description: "Cross-border payment infrastructure for emerging markets",
    logo: "https://logo.clearbit.com/wise.com",
  },
  {
    id: 10,
    name: "GenomeLink",
    website: "https://23andme.com",
    industry: "HealthTech",
    location: "San Diego, CA",
    founded: "2020",
    employees: "25-55",
    description: "Personalized medicine through genomic analysis",
    logo: "https://logo.clearbit.com/23andme.com",
  },
  {
    id: 11,
    name: "BuildStack",
    website: "https://procore.com",
    industry: "SaaS",
    location: "Atlanta, GA",
    founded: "2019",
    employees: "60-120",
    description: "Project management for construction companies",
    logo: "https://logo.clearbit.com/procore.com",
  },
  {
    id: 12,
    name: "Solaris Energy",
    website: "https://sunrun.com",
    industry: "CleanTech",
    location: "Portland, OR",
    founded: "2022",
    employees: "12-25",
    description: "Community solar subscription platform",
    logo: "https://logo.clearbit.com/sunrun.com",
  },
  {
    id: 13,
    name: "CodeCraft",
    website: "https://codecademy.com",
    industry: "EdTech",
    location: "Raleigh, NC",
    founded: "2021",
    employees: "15-30",
    description: "Interactive coding bootcamp for kids",
    logo: "https://logo.clearbit.com/codecademy.com",
  },
  {
    id: 14,
    name: "ShieldOps",
    website: "https://okta.com",
    industry: "Cybersecurity",
    location: "Dallas, TX",
    founded: "2020",
    employees: "35-70",
    description: "Automated security compliance monitoring",
    logo: "https://logo.clearbit.com/okta.com",
  },
  {
    id: 15,
    name: "AgriSense",
    website: "https://johndeere.com",
    industry: "AgTech",
    location: "Omaha, NE",
    founded: "2021",
    employees: "10-20",
    description: "IoT sensors for precision agriculture",
    logo: "https://logo.clearbit.com/johndeere.com",
  }
];

export default mockCompanies;